import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  es: {
    // Ajustes de cuenta
    ajustes_cuenta: "Ajustes de Cuenta",
    ajustes_description: "Administra tu configuración personal y preferencias del sistema",
    direccion_correo: "Dirección de correo",
    correo_desc: "Actualiza el correo electrónico asociado a tu cuenta para notificaciones y acceso.",
    nuevo_correo: "Nuevo correo electrónico",
    guardar_correo: "Guardar Correo",
    cambiar_contrasena: "Cambiar Contraseña",
    contrasena_desc: "Es recomendable usar una contraseña segura que no utilices en otros sitios.",
    contrasena_actual: "Contraseña actual",
    nueva_contrasena: "Nueva contraseña",
    actualizar_contrasena: "Actualizar Contraseña",
    preferencias_tema: "Preferencias de Tema",
    tema_desc: "Cambia la apariencia del sistema entre el modo claro y oscuro.",
    cerrar_sesion: "Cerrar Sesión",
    cerrar_sesion_desc: "Finalizará tu sesión en el sistema. Tendrás que volver a ingresar tus credenciales para acceder.",
    cerrar_sesion_btn: "Cerrar sesión de forma segura",
    // Idioma
    idioma: "Idioma",
    idioma_desc: "Selecciona el idioma preferido para la interfaz del sistema.",
    seleccionar_idioma: "Seleccionar idioma",
    // Alert messages
    ingresa_correo: "Ingresa un correo",
    correo_actualizado: "Correo actualizado correctamente",
    error_correo: "Error al actualizar correo",
    llena_campos: "Llena todos los campos",
    contrasena_actualizada: "Contraseña actualizada correctamente",
    error_contrasena: "Error al actualizar contraseña. Verifica tu contraseña actual.",
    
    // Navigation
    inicio: "Inicio",
    dispositivos: "Dispositivos",
    correo: "Correo",
    calendario: "Calendario",
    consulta_filtros: "Consulta con Filtros",
    registrar_salida: "Registrar Salida",
    generar_reportes: "Generar Reportes",
    estadisticas: "Estadisticas",
    equipo: "Equipo",
    gestion_mantenimiento: "Gestion de mantenimiento",
    prestamos: "Préstamos",
    usuarios: "Usuarios",
    ajustes_cuenta_nav: "Ajustes de Cuenta",
    paginas: "PAGINAS",
    
    // Dashboard
    dashboard_title: "Panel de Control",
    dashboard_welcome: "Bienvenido al Sistema",
    dashboard_stats: "Estadísticas Rápidas",
    total_dispositivos: "Total Dispositivos",
    dispositivos_activos: "Dispositivos Activos",
    prestamos_activos: "Préstamos Activos",
    mantenimientos_pendientes: "Mantenimientos Pendientes",
    
    // Dispositivos
    dispositivos_title: "Gestión de Dispositivos",
    agregar_dispositivo: "Agregar Dispositivo",
    buscar_dispositivo: "Buscar Dispositivo",
    nombre_dispositivo: "Nombre del Dispositivo",
    tipo_dispositivo: "Tipo de Dispositivo",
    estado_dispositivo: "Estado",
    disponible: "Disponible",
    prestado: "Prestado",
    mantenimiento: "En Mantenimiento",
    guardar: "Guardar",
    cancelar: "Cancelar",
    editar: "Editar",
    eliminar: "Eliminar",
    
    // Préstamos
    prestamos_title: "Gestión de Préstamos",
    nuevo_prestamo: "Nuevo Préstamo",
    devolver_dispositivo: "Devolver Dispositivo",
    fecha_prestamo: "Fecha de Préstamo",
    fecha_devolucion: "Fecha de Devolución",
    solicitante: "Solicitante",
    
    // Mantenimiento
    mantenimiento_title: "Mantenimiento de Dispositivos",
    nuevo_mantenimiento: "Nuevo Mantenimiento",
    descripcion: "Descripción",
    fecha_mantenimiento: "Fecha de Mantenimiento",
    tecnico_asignado: "Técnico Asignado",
    
    // Reportes
    reportes_title: "Generación de Reportes",
    tipo_reporte: "Tipo de Reporte",
    generar_reporte: "Generar Reporte",
    reporte_dispositivos: "Reporte de Dispositivos",
    reporte_prestamos: "Reporte de Préstamos",
    reporte_mantenimiento: "Reporte de Mantenimiento",
    
    // Estadísticas
    estadisticas_title: "Estadísticas del Sistema",
    graficos: "Gráficos",
    tabla_datos: "Tabla de Datos",
    periodo: "Período",
    
    // Usuarios
    usuarios_title: "Gestión de Usuarios",
    nuevo_usuario: "Nuevo Usuario",
    nombre_usuario: "Nombre de Usuario",
    email_usuario: "Correo Electrónico",
    rol_usuario: "Rol",
    admin: "Administrador",
    tecnico: "Técnico",
    usuario_normal: "Usuario",
    
    // Equipo
    equipo_title: "Gestión de Equipo",
    miembro_equipo: "Miembro del Equipo",
    cargo: "Cargo",
    
    // Calendario
    calendario_title: "Calendario de Eventos",
    evento: "Evento",
    agregar_evento: "Agregar Evento",
    
    // Correo
    correo_title: "Gestión de Correo",
    nuevo_correo: "Nuevo Correo",
    asunto: "Asunto",
    mensaje: "Mensaje",
    enviar: "Enviar",
    
    // Consulta con Filtros
    consulta_filtros_title: "Consulta con Filtros",
    aplicar_filtros: "Aplicar Filtros",
    limpiar_filtros: "Limpiar Filtros",
    resultados: "Resultados",
    
    // Gestion Mantenimiento
    gestion_mantenimiento_title: "Gestión de Mantenimiento",
    asignar_tecnico: "Asignar Técnico",
    actualizar_estado: "Actualizar Estado",
    
    // Historial
    historial_title: "Historial de Dispositivo",
    detalle: "Detalle",
    sin_datos: "No hay datos disponibles",
    cargar_mas: "Cargar más",
    
    // Comunes
    buscar: "Buscar",
    filtrar: "Filtrar",
    exportar: "Exportar",
    imprimir: "Imprimir",
    cerrar: "Cerrar",
    aceptar: "Aceptar",
    confirmar: "Confirmar",
    si: "Sí",
    no: "No",
    error: "Error",
    exito: "Éxito",
    informacion: "Información",
    advertencia: "Advertencia",

    // Home
    home_inicio: "Inicio",
    home_modulos: "Módulos",
    home_nosotros: "Nosotros",
    home_contacto: "Contacto",
    home_ingresar: "Ingresar",
    home_hero_tag: "Control inteligente de equipos",
    home_hero_title1: "Gestión de",
    home_hero_title2: "dispositivos electrónicos",
    home_hero_title3: "sin complicaciones",
    home_hero_sub: "Registra dispositivos, gestiona su estado durante el mantenimiento y mantén trazabilidad completa desde la recepción hasta la entrega final.",
    home_hero_btn1: "Comenzar ahora ↗",
    home_hero_btn2: "Conocer más",
    home_sec_tag1: "¿Qué hace DeviceGuard?",
    home_sec_title1: "Todo lo que necesitas",
    home_sec_title1b: "en un solo lugar",
    home_sec_sub1: "Cada módulo está diseñado para facilitar la gestión diaria de equipos en tu empresa.",
    home_feat1_title: "Registro y control",
    home_feat1_desc: "Registra dispositivos de clientes con su información, estado y fecha de ingreso al sistema.",
    home_feat2_title: "Mantenimiento",
    home_feat2_desc: "Administra el proceso técnico y actualiza el estado de cada equipo durante su reparación.",
    home_feat3_title: "Salida de dispositivos",
    home_feat3_desc: "Controla la entrega de equipos y registra la fecha y hora de salida.",
    home_feat4_title: "Roles y accesos",
    home_feat4_desc: "Gestiona accesos según el rol: administrador, técnico o usuario.",
    home_sec_tag2: "Nosotros",
    home_sec_title2: "¿Quiénes somos?",
    home_about_p1: "DeviceGuard es un sistema diseñado para gestionar dispositivos electrónicos de clientes externos dentro de una empresa de mantenimiento.",
    home_about_p2: "Permite llevar control del proceso completo: desde el registro del equipo, su mantenimiento y hasta su entrega final, mejorando la organización y trazabilidad del servicio técnico.",
    home_about_item1_title: "Monitoreo en tiempo real",
    home_about_item1_desc: "Consulta el estado de cada equipo al instante desde cualquier dispositivo.",
    home_about_item2_title: "Fácil de usar",
    home_about_item2_desc: "Interfaz intuitiva sin curva de aprendizaje para cualquier usuario.",
    home_about_item3_title: "Seguro y confiable",
    home_about_item3_desc: "Acceso por roles con autenticación segura para proteger la información.",
    home_mission_title: "Nuestro objetivo",
    home_mission_sub: "Brindar una herramienta que facilite la gestión de dispositivos de clientes durante su proceso de mantenimiento, de forma organizada, segura y eficiente.",
    home_sec_tag3: "Misión",
    home_sec_title3: "Tecnología al servicio",
    home_sec_title3b: "del mantenimiento",
    home_sec_sub3: "Optimizar el control y seguimiento de dispositivos electrónicos en mantenimiento, garantizando trazabilidad desde su ingreso hasta su entrega final.",
    home_contact_tag: "Contacto",
    home_contact_title: "¿Tienes alguna pregunta?",
    home_contact_sub: "Estamos disponibles para apoyarte en el uso del sistema",
    home_contact_btn: "Ingresar al sistema ↗",

    // Login
    login_title: "Iniciar sesión",
    login_email_ph: "correo@deviceguard.com",
    login_pass_ph: "••••••••••",
    login_forgot: "¿Olvidaste tu contraseña?",
    login_btn_login: "Inicia sesión",
    login_btn_loading: "Iniciando sesión...",
    login_reg_title: "Crear cuenta",
    login_reg_name_ph: "Nombre completo",
    login_reg_email_ph: "Correo electrónico",
    login_reg_pass_ph: "Contraseña (mín. 6 caracteres)",
    login_reg_conf_ph: "Confirmar contraseña",
    login_btn_reg: "Crear cuenta",
    login_btn_reg_loading: "Creando cuenta...",
    login_rec_title: "Recuperar Contraseña",
    login_rec_sub: "Ingresa tu correo y te enviaremos las instrucciones.",
    login_btn_rec: "Enviar correo",
    login_btn_rec_loading: "Enviando...",
    login_res_title: "Restablecer Contraseña",
    login_res_pass_ph: "Nueva contraseña",
    login_res_conf_ph: "Confirmar nueva contraseña",
    login_btn_res: "Guardar contraseña",
    login_btn_res_loading: "Guardando...",
    login_panel_login_title: "¡Bienvenido!",
    login_panel_login_sub1: "¿No tienes cuenta aún?",
    login_panel_login_sub2: "Regístrate y comienza",
    login_panel_login_sub3: "a gestionar dispositivos",
    login_panel_login_btn: "Registrarse",
    login_panel_reg_title: "¡Bienvenido de nuevo!",
    login_panel_reg_sub1: "¿Ya tienes cuenta?",
    login_panel_reg_sub2: "Inicia sesión para",
    login_panel_reg_sub3: "continuar",
    login_panel_reg_btn: "Iniciar sesión",
    login_panel_rec_title: "Tranquilo",
    login_panel_rec_sub1: "Suele pasar.",
    login_panel_rec_sub2: "Ingresa tu correo y te ayudaremos",
    login_panel_rec_sub3: "a recuperar el acceso.",
    login_panel_rec_btn: "Volver al Login",
    login_panel_res_title: "Casi listo",
    login_panel_res_sub1: "Ingresa una nueva contraseña",
    login_panel_res_sub2: "para tu cuenta y asegúrate",
    login_panel_res_sub3: "de recordarla.",

    // Dashboard complementos
    dash_inicio: "Inicio",
    dash_total_equipos: "Total equipos",
    dash_listo_entrega: "Listo para Entrega",
    dash_en_revision: "En revisión",
    dash_en_mantenimiento: "En mantenimiento",
    dash_entregado: "Entregado",
    dash_total_reportes: "Total reportes",
    dash_usuarios_registrados: "usuarios registrados",
    dash_reportes_enviados: "Reportes enviados",
    dash_lista_dispositivos: "Lista de dispositivos",
    dash_buscar_ph: "Buscar nombre, serial, ubicación...",
    dash_todos_estados: "Todos los estados",
    dash_col_imagen: "Imagen",
    dash_col_nombre: "Nombre",
    dash_col_ubicacion: "Ubicación",
    dash_col_serial: "Serial",
    dash_col_fecha_reg: "Fecha registro",
    dash_col_estado: "Estado",
    dash_col_reg_por: "Registrado por",
    dash_no_dispositivos: "No hay dispositivos registrados",
    dash_limpiar: "Limpiar",

    // Correo complementos
    correo_mi_correo: "Mi Correo",
    correo_notificaciones: "Notificaciones",
    correo_enviados: "Enviados",
    correo_mensajeria: "Mensajería",
    correo_mensajes: "Mensajes",
    correo_historial: "Historial de correos enviados",
    correo_registros: "registros",
    correo_destinatario: "Destinatario",
    correo_no_hay: "No hay correos registrados",
    correo_selecciona_usuario: "Selecciona un usuario para iniciar una conversación",
    correo_no_mensajes: "Aún no hay mensajes. ¡Empieza la conversación!",
    correo_escribe_mensaje: "Escribe un mensaje...",
    correo_mensaje_enviado: "Mensaje enviado",
    correo_error_enviar: "Error al enviar mensaje",
    
    // Generales extras
    fecha: "Fecha",
    hora: "Hora",
    sin_resultados: "No hay resultados",

    // Equipo complementos
    equipo_add_usuario: "Añadir Usuario",
    equipo_mensaje: "Mensaje",
    equipo_lista_usuarios: "Lista de usuarios",
    equipo_buscar_ph: "Buscar por nombre o correo...",
    equipo_col_usuario: "Usuario",
    equipo_col_acciones: "Acciones",
    equipo_suspendido: "Suspendido",
    equipo_activar: "Activar",
    equipo_suspender: "Suspender",
    equipo_add_miembro: "Añadir Miembro del Equipo",
    equipo_subir_foto: "Subir Foto",
    equipo_form_pnombre: "Primer Nombre",
    equipo_form_apellido: "Apellido",
    equipo_form_telefono: "Número Telefónico",
    equipo_form_puesto: "Puesto de Trabajo",
    equipo_form_genero: "Género",
    equipo_form_pass: "Contraseña inicial",
    equipo_masculino: "Masculino",
    equipo_femenino: "Femenino",
    equipo_otro: "Otro",
    equipo_editar_usuario: "Editar Usuario",
    equipo_eliminar_pregunta: "¿Eliminar a",
    equipo_eliminar_advertencia: "Esta acción no se puede deshacer.",
    equipo_agregado: "Usuario agregado correctamente",
    equipo_err_agregar: "Error al agregar usuario",
    equipo_actualizado: "Usuario actualizado correctamente",
    equipo_err_actualizar: "Error al actualizar usuario",
    equipo_eliminado: "Usuario eliminado correctamente",
    equipo_err_eliminar: "Error al eliminar usuario",
    equipo_activado: "Usuario activado correctamente",
    equipo_desactivado: "Usuario desactivado correctamente",
    equipo_err_estado: "Error al cambiar estado del usuario",

    // Estadisticas
    estadisticas_title: "Estadísticas",
    estadisticas_cargando: "Cargando estadísticas...",
    estadisticas_filtros: "Filtros",
    estadisticas_anio: "Año",
    estadisticas_todos_anios: "Todos los años",
    estadisticas_mes: "Mes",
    estadisticas_principal: "principal",
    estadisticas_todos_meses: "Todos los meses",
    estadisticas_estado: "Estado",
    estadisticas_tipo_disp: "Tipo de dispositivo",
    estadisticas_todos_tipos: "Todos los tipos",
    estadisticas_resultado: "resultado",
    estadisticas_resultados: "resultados",
    estadisticas_distribucion: "Distribución por estado",
    estadisticas_total: "total",
    estadisticas_cantidad: "Cantidad por estado",
    estadisticas_registros: "Registros por mes",
    estadisticas_disp_tipo: "Dispositivos por tipo",
    estadisticas_sin_datos: "Sin datos para este filtro",
    estadisticas_pct_total: "% del total",
    estadisticas_no_disp_filtros: "No hay dispositivos para los filtros seleccionados",
    estadisticas_col_tipo: "Tipo",
    estadisticas_col_marca: "Marca",

    // GestionMantenimiento
    mant_title: "Gestión de mantenimiento",
    mant_error_actualizar: "Error al actualizar estado",
    mant_col_estado_actual: "Estado actual",
    mant_col_cambiar_estado: "Cambiar estado",
    mant_cambiar_estado: "cambiar estado",

    // HistorialDispositivo
    historial_err_guardar: "Error al guardar la observación",
    historial_cargando: "Cargando información del equipo...",
    historial_no_disp: "No se encontró el dispositivo.",
    historial_title: "Historial de Equipo",
    historial_volver: "← Volver al Dashboard",
    historial_nombre_modelo: "Nombre / Modelo",
    historial_mantenimientos: "Historial de Mantenimientos",
    historial_sin_mantenimientos: "No hay registros de mantenimiento para este equipo.",
    historial_obs_title: "Observaciones / Trabajos Realizados",
    historial_add_obs_ph: "Añadir nueva observación, diagnóstico o trabajo realizado...",
    historial_guardando: "Guardando...",
    historial_registrar_obs: "+ Registrar Observación",
    historial_sin_observaciones: "No hay observaciones registradas para este equipo aún.",
    historial_sistema: "Sistema",

    // Mantenimiento
    mant_eliminar_confirm: "¿Seguro que deseas eliminar este registro de mantenimiento?",
    mant_title_disp: "Mantenimiento de Dispositivos",
    mant_actualizar: "Actualizar Mantenimiento",
    mant_registrar_nuevo: "Registrar Nuevo Mantenimiento",
    mant_form_dispositivo: "Dispositivo:",
    mant_selecciona_disp: "Selecciona un dispositivo",
    mant_form_desc: "Descripción / Fallo reportado:",
    mant_form_costo: "Costo Estimado/Final ($):",
    mant_form_estado: "Estado del Mantenimiento:",
    mant_en_proceso: "En Proceso",
    mant_completado: "Completado",
    mant_cancelado: "Cancelado",
    guardar_cambios: "Guardar Cambios",
    mant_registrar_ingreso: "Registrar Ingreso Mantenimiento",
    mant_col_disp: "Dispositivo",
    mant_col_costos: "Costos",
    mant_col_fechas: "Fechas",
    mant_inicio: "Inicio: ",
    mant_fin: "Fin: ",
    mant_ver_editar: "Ver/Editar",
    mant_sin_registros: "No hay registros de mantenimiento",

    // Prestamos
    prestamo_eliminar_confirm: "¿Seguro que deseas eliminar el registro de este préstamo?",
    prestamo_title: "Gestión de Préstamos",
    prestamo_actualizar_estado: "Actualizar Estado Préstamo",
    prestamo_registrar_nuevo: "Registrar Nuevo Préstamo",
    prestamo_usuario: "Usuario (Prestatario):",
    prestamo_selecciona_usuario: "Selecciona un usuario",
    prestamo_estado_prestamo: "Estado del Préstamo:",
    prestamo_activo: "Activo",
    prestamo_devuelto: "Devuelto",
    prestamo_atrasado: "Atrasado",
    prestamo_btn_actualizar: "Actualizar Estado",
    prestamo_btn_registrar: "Registrar Préstamo",
    prestamo_historial: "Historial de Préstamos",
    prestamo_col_fecha_prestamo: "Fecha Préstamo",
    prestamo_col_fecha_devolucion: "Fecha Devolución",
    prestamo_resolver: "Resolver",
    prestamo_no_registrados: "No hay préstamos registrados",

    // Registrar salida
    salida_disp_no_existe: "El dispositivo no existe",
    salida_solo_mantenimiento: "Solo puedes registrar salida si el dispositivo está en mantenimiento.",
    salida_err_registrar: "Error al registrar salida",
    salida_confirm_finalizar: "¿Finalizar proceso del dispositivo?",
    salida_title: "Registrar Salida de Dispositivos",
    salida_subtitle: "Gestiona la salida de equipos cuando finalizan su proceso",
    salida_btn_registrar: "Registrar Salida",
    salida_editar: "Editar salida",
    salida_modal_title: "Registrar salida de dispositivo",
    cerrar: "Cerrar",
    salida_modal_serial: "Serial del dispositivo",
    salida_modal_serial_ph: "Ej: ABC-123456",
    salida_modal_info: "Información",
    salida_modal_info_desc: "La salida se registra automáticamente (fecha, hora y estado).",
    salida_btn_actualizar: "Actualizar salida",
    salida_buscar_ph: "Buscar por serial, nombre...",
    salida_col_fecha_ent: "Fecha entrada",
    salida_col_fecha_sal: "Fecha salida",
    salida_no_registros: "No hay registros",

    // Reportes
    reportes_err_fechas: "Por favor selecciona las fechas Desde y Hasta para continuar.",
    reportes_err_excel_usuarios: "Error al descargar Excel de usuarios",
    reportes_err_pdf_usuarios: "Error al descargar PDF de usuarios",
    reportes_err_excel_disp: "Error al descargar Excel de dispositivos",
    reportes_err_pdf_disp: "Error al descargar PDF de dispositivos",
    id: "ID",
    reportes_fecha_creacion: "Fecha de creación",
    reportes_title: "Generar Reportes",
    reportes_exportar: "Exportar reportes",
    reportes_subtitle: "Genera los reportes que vayan según tu necesidad",
    reportes_reg_vista: "Registros en vista previa",
    reportes_generados: "Reportes generados",
    reportes_vista_previa: "Vista previa",
    reportes_buscar_usu: "Buscar por nombre, correo o rol...",
    reportes_buscar_disp: "Buscar por nombre, serial, estado o usuario...",
    reportes_cargando: "Cargando datos...",
    reportes_no_registros: "No se encontraron registros.",
    reportes_rep_usuarios: "Reporte Usuarios",
    reportes_todos: "Todos",
    reportes_tecnicos: "Técnicos",
    reportes_desde: "Desde",
    reportes_hasta: "Hasta",
    reportes_gen_excel: "Generar Excel",
    reportes_gen_pdf: "Generar PDF",
    reportes_rep_disp: "Reporte Dispositivos",
    reportes_vista_usu: "Vista previa — Usuarios",
    reportes_vista_disp: "Vista previa — Dispositivos",
    reportes_han_sido_generados: "reportes han sido generados en total",

    // Usuarios
    usu_eliminar_confirm: "¿Seguro que deseas eliminar este usuario?",
    usu_title: "Gestión de Usuarios",
    usu_registrar_nuevo: "Registrar Nuevo Usuario",
    usu_form_nombre: "Nombre:",
    usu_form_correo: "Correo Electrónico:",
    usu_form_pass: "Contraseña:",
    usu_form_rol: "Rol:",
    usu_estandar: "Usuario Estándar",
    usu_actualizar: "Actualizar Usuario",
    usu_registrar: "Registrar Usuario",
    usu_no_registrados: "No hay usuarios registrados",

    // Perfil
    perfil_pwd_actualizada: "Contraseña actualizada",
    perfil_err_pwd: "Error al cambiar contraseña",
    perfil_cambiar_pwd: "Cambiar contraseña",
    perfil_nueva_pwd: "Nueva contraseña",
    perfil_btn_pwd: "Actualizar contraseña",
    perfil_correo_actualizado: "Correo actualizado correctamente",
    perfil_err_correo: "Error al actualizar correo",
    perfil_cambiar_correo: "Cambiar Correo",
    perfil_nuevo_correo: "Nuevo correo",
    perfil_btn_correo: "Actualizar correo",

    // Calendario
    cal_titulo: "Calendario",
    cal_hoy: "Hoy",
    cal_agregar_evento: "+ Agregar evento",
    cal_sin_eventos_dia: "Sin eventos este día",
    cal_sin_eventos_mes: "Sin eventos este mes",
    cal_eventos_mes: "Eventos del mes",
    cal_entrega: "Entrega:",
    cal_sin_ubicacion: "Sin ubicación",
    cal_mas: "más",
    cal_registrar_entrega: "Registrar entrega",
    cal_registrar_mantenimiento: "Registrar mantenimiento",
    cal_registrar_salida: "Registrar salida",
    cal_modal_registrar_entrega: "Registrar Entrega",
    cal_modal_registrar_mantenimiento: "Registrar Mantenimiento",
    cal_modal_registrar_salida: "Registrar Salida",
    cal_accion_registrada: "Acción registrada correctamente.",
    cal_err_registrar_accion: "Error al registrar la acción. Intenta de nuevo.",
    cal_modal_agregar_title: "Agregar fecha comprometida",
    cal_dispositivo_label: "Dispositivo",
    cal_selecciona_equipo: "Selecciona un equipo...",
    cal_fecha_estimada: "Fecha estimada de entrega",
    cal_nota_opcional: "Nota (opcional)",
    cal_nota_ph: "Ej: esperando repuesto, cliente llama el viernes...",
    cal_guardar: "Guardar ↗",
    cal_confirmar_accion: "¿Confirmas esta acción? El estado cambiará a",
    cal_guardando: "Guardando…",
    cal_confirmar_btn: "✓ Confirmar",
    cal_detalle_equipo: "Detalle del equipo",
    ene: "Enero", feb: "Febrero", mar: "Marzo", abr: "Abril", may: "Mayo", jun: "Junio", jul: "Julio", ago: "Agosto", sep: "Septiembre", oct: "Octubre", nov: "Noviembre", dic: "Diciembre",
    dom: "Dom", lun: "Lun", mar_dia: "Mar", mie: "Mié", jue: "Jue", vie: "Vie", sab: "Sáb",

    // Asignaciones
    asignacion_title: "Asignación de Tareas",
    asignacion_sin_tecnicos: "No hay técnicos disponibles.",
    asignacion_sin_dispositivos: "No hay dispositivos pendientes por asignar.",
    asignacion_tecnicos_disponibles: "Técnicos Disponibles",
    asignacion_tareas_activas: "tareas activas",
    asignacion_btn_asignar: "Asignar",
    asignacion_seleccionar_tecnico: "Seleccionar técnico...",
    asignacion_exito: "Dispositivo asignado exitosamente",
    asignacion_error: "Error al asignar dispositivo",
    asignacion_pendientes: "Dispositivos por Asignar",

    // Dispositivos (claves específicas del módulo)
    disp_banner_titulo: "Registra\nNuevos Dispositivos",
    disp_banner_sub: "Registra y guarda nuevos dispositivos en el sistema",
    disp_reingresar: "Reingresar Dispositivo",
    disp_lista: "Lista de dispositivos",
    disp_registrados: "registrados",
    disp_buscar_placeholder: "Buscar por nombre, serial o marca...",
    disp_todos_estados: "Todos los estados",
    disp_serial: "Serial",
    disp_marca: "Marca",
    disp_ubicacion: "Ubicación",
    disp_fecha_hora: "Fecha / Hora",
    disp_acciones: "Acciones",
    disp_en_revision: "En Revisión",
    disp_imagen: "Imagen del dispositivo",
    disp_guardando: "Guardando...",
    disp_actualizar: "Actualizar dispositivo",
    disp_editar: "Editar dispositivo",
    disp_registrar_nuevo: "Registrar nuevo dispositivo",
    disp_no_registrado: "El dispositivo no está registrado",
    disp_error_reingreso: "Error al reingresar el dispositivo",
    disp_serial_label: "Serial del dispositivo",
    disp_procesando: "Procesando...",
    disp_confirmar_reingreso_btn: "Confirmar Reingreso",
    disp_sin_resultados: "No hay dispositivos que coincidan con los filtros",
    disp_confirmar_reingreso: "¿Deseas reingresar este dispositivo?",
    disp_estado_cambiara: "Su estado cambiará a",
    disp_descripcion: "Descripción del equipo",
    disp_col_nombre: "NOMBRE DEL DISPOSITIVO",
    disp_col_tipo: "Tipo",
    disp_col_nombre_disp: "Nombre del Dispositivo",

    // Claves adicionales
    correo_col_correo: "Correo",
    rol: "Rol",
    agregar: "Agregar",
    cargando_info: "Cargando información...",
    dash_usuarios: "Usuarios",
    dash_dispositivos: "Dispositivos",
    rpt_rol_superadmin: "Super Admin",
    rpt_rol_tecnico: "Técnico",
    rpt_rol_usuario: "Usuario",

    // Sidebar
    sidebar_simular_usuario: "Simular usuario",
    sidebar_simulando_como: "👁 Simulando como:",
    sidebar_volver_admin: "← Volver a Super Admin",
    sidebar_seleccionar_usuario: "Seleccionar usuario...",
    sidebar_buscar_usuario: "Buscar usuario o técnico...",
    sidebar_disp_asignados: "Dispositivos asignados",
    sidebar_sin_disp_pendientes: "Sin dispositivos pendientes",
    sidebar_disp_asignado: "Dispositivo asignado",
    sidebar_al_confirmar: "Al confirmar, el dispositivo pasará a",
    sidebar_en_mantenimiento_bold: "En Mantenimiento",
    sidebar_comenzaras: "y comenzarás a trabajar en él.",
    sidebar_guardando: "Guardando...",
    sidebar_iniciar_mant: "✓ Iniciar mantenimiento",
    sidebar_tecnicos: "Técnicos",
    sidebar_usuarios: "Usuarios",
  },
  en: {
    // Account settings
    ajustes_cuenta: "Account Settings",
    ajustes_description: "Manage your personal configuration and system preferences",
    direccion_correo: "Email Address",
    correo_desc: "Update the email address associated with your account for notifications and access.",
    nuevo_correo: "New email address",
    guardar_correo: "Save Email",
    cambiar_contrasena: "Change Password",
    contrasena_desc: "It's recommended to use a secure password that you don't use on other sites.",
    contrasena_actual: "Current password",
    nueva_contrasena: "New password",
    actualizar_contrasena: "Update Password",
    preferencias_tema: "Theme Preferences",
    tema_desc: "Change the system appearance between light and dark mode.",
    cerrar_sesion: "Logout",
    cerrar_sesion_desc: "This will end your session in the system. You'll need to enter your credentials again to access.",
    cerrar_sesion_btn: "Logout safely",
    // Language
    idioma: "Language",
    idioma_desc: "Select your preferred language for the system interface.",
    seleccionar_idioma: "Select language",
    // Alert messages
    ingresa_correo: "Enter an email",
    correo_actualizado: "Email updated successfully",
    error_correo: "Error updating email",
    llena_campos: "Fill all fields",
    contrasena_actualizada: "Password updated successfully",
    error_contrasena: "Error updating password. Verify your current password.",
    
    // Navigation
    inicio: "Home",
    dispositivos: "Devices",
    correo: "Email",
    calendario: "Calendar",
    consulta_filtros: "Search with Filters",
    registrar_salida: "Register Output",
    generar_reportes: "Generate Reports",
    estadisticas: "Statistics",
    equipo: "Team",
    gestion_mantenimiento: "Maintenance Management",
    prestamos: "Loans",
    usuarios: "Users",
    ajustes_cuenta_nav: "Account Settings",
    paginas: "PAGES",
    
    // Dashboard
    dashboard_title: "Control Panel",
    dashboard_welcome: "Welcome to the System",
    dashboard_stats: "Quick Statistics",
    total_dispositivos: "Total Devices",
    dispositivos_activos: "Active Devices",
    prestamos_activos: "Active Loans",
    mantenimientos_pendientes: "Pending Maintenance",
    
    // Dispositivos
    dispositivos_title: "Device Management",
    agregar_dispositivo: "Add Device",
    buscar_dispositivo: "Search Device",
    nombre_dispositivo: "Device Name",
    tipo_dispositivo: "Device Type",
    estado_dispositivo: "Status",
    disponible: "Available",
    prestado: "Loaned",
    mantenimiento: "In Maintenance",
    guardar: "Save",
    cancelar: "Cancel",
    editar: "Edit",
    eliminar: "Delete",
    
    // Préstamos
    prestamos_title: "Loan Management",
    nuevo_prestamo: "New Loan",
    devolver_dispositivo: "Return Device",
    fecha_prestamo: "Loan Date",
    fecha_devolucion: "Return Date",
    solicitante: "Applicant",
    
    // Mantenimiento
    mantenimiento_title: "Device Maintenance",
    nuevo_mantenimiento: "New Maintenance",
    descripcion: "Description",
    fecha_mantenimiento: "Maintenance Date",
    tecnico_asignado: "Assigned Technician",
    
    // Reportes
    reportes_title: "Report Generation",
    tipo_reporte: "Report Type",
    generar_reporte: "Generate Report",
    reporte_dispositivos: "Device Report",
    reporte_prestamos: "Loan Report",
    reporte_mantenimiento: "Maintenance Report",
    
    // Estadísticas
    estadisticas_title: "System Statistics",
    graficos: "Charts",
    tabla_datos: "Data Table",
    periodo: "Period",
    
    // Usuarios
    usuarios_title: "User Management",
    nuevo_usuario: "New User",
    nombre_usuario: "Username",
    email_usuario: "Email Address",
    rol_usuario: "Role",
    admin: "Administrator",
    tecnico: "Technician",
    usuario_normal: "User",
    
    // Equipo
    equipo_title: "Team Management",
    miembro_equipo: "Team Member",
    cargo: "Position",
    
    // Calendario
    calendario_title: "Event Calendar",
    evento: "Event",
    agregar_evento: "Add Event",
    
    // Correo
    correo_title: "Email Management",
    nuevo_correo: "New Email",
    asunto: "Subject",
    mensaje: "Message",
    enviar: "Send",
    
    // Consulta con Filtros
    consulta_filtros_title: "Search with Filters",
    aplicar_filtros: "Apply Filters",
    limpiar_filtros: "Clear Filters",
    resultados: "Results",
    
    // Gestion Mantenimiento
    gestion_mantenimiento_title: "Maintenance Management",
    asignar_tecnico: "Assign Technician",
    actualizar_estado: "Update Status",
    
    // Historial
    historial_title: "Device History",
    detalle: "Detail",
    sin_datos: "No data available",
    cargar_mas: "Load more",
    
    // Comunes
    buscar: "Search",
    filtrar: "Filter",
    exportar: "Export",
    imprimir: "Print",
    cerrar: "Close",
    aceptar: "Accept",
    confirmar: "Confirm",
    si: "Yes",
    no: "No",
    error: "Error",
    exito: "Success",
    informacion: "Information",
    advertencia: "Warning",

    // Home
    home_inicio: "Home",
    home_modulos: "Modules",
    home_nosotros: "About Us",
    home_contacto: "Contact",
    home_ingresar: "Login",
    home_hero_tag: "Smart equipment control",
    home_hero_title1: "Management of",
    home_hero_title2: "electronic devices",
    home_hero_title3: "made simple",
    home_hero_sub: "Register devices, manage their status during maintenance, and keep complete traceability from reception to final delivery.",
    home_hero_btn1: "Get started ↗",
    home_hero_btn2: "Learn more",
    home_sec_tag1: "What does DeviceGuard do?",
    home_sec_title1: "Everything you need",
    home_sec_title1b: "in one place",
    home_sec_sub1: "Each module is designed to facilitate the daily management of equipment in your company.",
    home_feat1_title: "Registration and control",
    home_feat1_desc: "Register client devices with their information, status, and system entry date.",
    home_feat2_title: "Maintenance",
    home_feat2_desc: "Manage the technical process and update the status of each device during repair.",
    home_feat3_title: "Device output",
    home_feat3_desc: "Control equipment delivery and record the date and time of departure.",
    home_feat4_title: "Roles and access",
    home_feat4_desc: "Manage access according to role: administrator, technician, or user.",
    home_sec_tag2: "About Us",
    home_sec_title2: "Who are we?",
    home_about_p1: "DeviceGuard is a system designed to manage external clients' electronic devices within a maintenance company.",
    home_about_p2: "It allows tracking of the complete process: from equipment registration, its maintenance, and up to its final delivery, improving the organization and traceability of the technical service.",
    home_about_item1_title: "Real-time monitoring",
    home_about_item1_desc: "Check the status of each device instantly from any device.",
    home_about_item2_title: "Easy to use",
    home_about_item2_desc: "Intuitive interface with no learning curve for any user.",
    home_about_item3_title: "Secure and reliable",
    home_about_item3_desc: "Role-based access with secure authentication to protect information.",
    home_mission_title: "Our objective",
    home_mission_sub: "Provide a tool that facilitates the management of client devices during their maintenance process, in an organized, secure, and efficient way.",
    home_sec_tag3: "Mission",
    home_sec_title3: "Technology serving",
    home_sec_title3b: "maintenance",
    home_sec_sub3: "Optimize the control and tracking of electronic devices under maintenance, ensuring traceability from entry to final delivery.",
    home_contact_tag: "Contact",
    home_contact_title: "Do you have any questions?",
    home_contact_sub: "We are available to support you in using the system",
    home_contact_btn: "Enter system ↗",

    // Login
    login_title: "Log in",
    login_email_ph: "email@deviceguard.com",
    login_pass_ph: "••••••••••",
    login_forgot: "Forgot your password?",
    login_btn_login: "Log in",
    login_btn_loading: "Logging in...",
    login_reg_title: "Create account",
    login_reg_name_ph: "Full name",
    login_reg_email_ph: "Email address",
    login_reg_pass_ph: "Password (min. 6 characters)",
    login_reg_conf_ph: "Confirm password",
    login_btn_reg: "Create account",
    login_btn_reg_loading: "Creating account...",
    login_rec_title: "Recover Password",
    login_rec_sub: "Enter your email and we will send you the instructions.",
    login_btn_rec: "Send email",
    login_btn_rec_loading: "Sending...",
    login_res_title: "Reset Password",
    login_res_pass_ph: "New password",
    login_res_conf_ph: "Confirm new password",
    login_btn_res: "Save password",
    login_btn_res_loading: "Saving...",
    login_panel_login_title: "Welcome!",
    login_panel_login_sub1: "Don't have an account yet?",
    login_panel_login_sub2: "Sign up and start",
    login_panel_login_sub3: "managing devices",
    login_panel_login_btn: "Sign up",
    login_panel_reg_title: "Welcome back!",
    login_panel_reg_sub1: "Already have an account?",
    login_panel_reg_sub2: "Log in to",
    login_panel_reg_sub3: "continue",
    login_panel_reg_btn: "Log in",
    login_panel_rec_title: "Don't worry",
    login_panel_rec_sub1: "It happens.",
    login_panel_rec_sub2: "Enter your email and we'll help you",
    login_panel_rec_sub3: "recover access.",
    login_panel_rec_btn: "Back to Login",
    login_panel_res_title: "Almost there",
    login_panel_res_sub1: "Enter a new password",
    login_panel_res_sub2: "for your account and make sure",
    login_panel_res_sub3: "to remember it.",

    // Dashboard complementos
    dash_inicio: "Home",
    dash_total_equipos: "Total equipment",
    dash_listo_entrega: "Ready for Delivery",
    dash_en_revision: "Under Review",
    dash_en_mantenimiento: "In Maintenance",
    dash_entregado: "Delivered",
    dash_total_reportes: "Total reports",
    dash_usuarios_registrados: "registered users",
    dash_reportes_enviados: "Reports sent",
    dash_lista_dispositivos: "Device list",
    dash_buscar_ph: "Search name, serial, location...",
    dash_todos_estados: "All statuses",
    dash_col_imagen: "Image",
    dash_col_nombre: "Name",
    dash_col_ubicacion: "Location",
    dash_col_serial: "Serial",
    dash_col_fecha_reg: "Registration date",
    dash_col_estado: "Status",
    dash_col_reg_por: "Registered by",
    dash_no_dispositivos: "No registered devices",
    dash_limpiar: "Clear",

    // Correo complementos
    correo_mi_correo: "My Mail",
    correo_notificaciones: "Notifications",
    correo_enviados: "Sent",
    correo_mensajeria: "Messaging",
    correo_mensajes: "Messages",
    correo_historial: "Sent emails history",
    correo_registros: "records",
    correo_destinatario: "Recipient",
    correo_no_hay: "No registered emails",
    correo_selecciona_usuario: "Select a user to start a conversation",
    correo_no_mensajes: "No messages yet. Start the conversation!",
    correo_escribe_mensaje: "Type a message...",
    correo_mensaje_enviado: "Message sent",
    correo_error_enviar: "Error sending message",
    
    // Generales extras
    fecha: "Date",
    hora: "Time",
    sin_resultados: "No results found",

    // Equipo complementos
    equipo_add_usuario: "Add User",
    equipo_mensaje: "Message",
    equipo_lista_usuarios: "User list",
    equipo_buscar_ph: "Search by name or email...",
    equipo_col_usuario: "User",
    equipo_col_acciones: "Actions",
    equipo_suspendido: "Suspended",
    equipo_activar: "Activate",
    equipo_suspender: "Suspend",
    equipo_add_miembro: "Add Team Member",
    equipo_subir_foto: "Upload Photo",
    equipo_form_pnombre: "First Name",
    equipo_form_apellido: "Last Name",
    equipo_form_telefono: "Phone Number",
    equipo_form_puesto: "Job Title",
    equipo_form_genero: "Gender",
    equipo_form_pass: "Initial Password",
    equipo_masculino: "Male",
    equipo_femenino: "Female",
    equipo_otro: "Other",
    equipo_editar_usuario: "Edit User",
    equipo_eliminar_pregunta: "Delete",
    equipo_eliminar_advertencia: "This action cannot be undone.",
    equipo_agregado: "User successfully added",
    equipo_err_agregar: "Error adding user",
    equipo_actualizado: "User successfully updated",
    equipo_err_actualizar: "Error updating user",
    equipo_eliminado: "User successfully deleted",
    equipo_err_eliminar: "Error deleting user",
    equipo_activado: "User successfully activated",
    equipo_desactivado: "User successfully deactivated",
    equipo_err_estado: "Error changing user status",

    // Estadisticas
    estadisticas_title: "Statistics",
    estadisticas_cargando: "Loading statistics...",
    estadisticas_filtros: "Filters",
    estadisticas_anio: "Year",
    estadisticas_todos_anios: "All years",
    estadisticas_mes: "Month",
    estadisticas_principal: "main",
    estadisticas_todos_meses: "All months",
    estadisticas_estado: "Status",
    estadisticas_tipo_disp: "Device type",
    estadisticas_todos_tipos: "All types",
    estadisticas_resultado: "result",
    estadisticas_resultados: "results",
    estadisticas_distribucion: "Distribution by status",
    estadisticas_total: "total",
    estadisticas_cantidad: "Amount by status",
    estadisticas_registros: "Records per month",
    estadisticas_disp_tipo: "Devices by type",
    estadisticas_sin_datos: "No data for this filter",
    estadisticas_pct_total: "% of total",
    estadisticas_no_disp_filtros: "No devices for selected filters",
    estadisticas_col_tipo: "Type",
    estadisticas_col_marca: "Brand",

    // GestionMantenimiento
    mant_title: "Maintenance Management",
    mant_error_actualizar: "Error updating status",
    mant_col_estado_actual: "Current status",
    mant_col_cambiar_estado: "Change status",
    mant_cambiar_estado: "change status",

    // HistorialDispositivo
    historial_err_guardar: "Error saving observation",
    historial_cargando: "Loading equipment information...",
    historial_no_disp: "Device not found.",
    historial_title: "Equipment History",
    historial_volver: "← Back to Dashboard",
    historial_nombre_modelo: "Name / Model",
    historial_mantenimientos: "Maintenance History",
    historial_sin_mantenimientos: "No maintenance records for this equipment.",
    historial_obs_title: "Observations / Work Done",
    historial_add_obs_ph: "Add new observation, diagnosis, or work done...",
    historial_guardando: "Saving...",
    historial_registrar_obs: "+ Register Observation",
    historial_sin_observaciones: "No observations recorded for this equipment yet.",
    historial_sistema: "System",

    // Mantenimiento
    mant_eliminar_confirm: "Are you sure you want to delete this maintenance record?",
    mant_title_disp: "Device Maintenance",
    mant_actualizar: "Update Maintenance",
    mant_registrar_nuevo: "Register New Maintenance",
    mant_form_dispositivo: "Device:",
    mant_selecciona_disp: "Select a device",
    mant_form_desc: "Description / Reported failure:",
    mant_form_costo: "Estimated/Final Cost ($):",
    mant_form_estado: "Maintenance Status:",
    mant_en_proceso: "In Process",
    mant_completado: "Completed",
    mant_cancelado: "Cancelled",
    guardar_cambios: "Save Changes",
    mant_registrar_ingreso: "Register Maintenance Entry",
    mant_col_disp: "Device",
    mant_col_costos: "Costs",
    mant_col_fechas: "Dates",
    mant_inicio: "Start: ",
    mant_fin: "End: ",
    mant_ver_editar: "View/Edit",
    mant_sin_registros: "No maintenance records",

    // Prestamos
    prestamo_eliminar_confirm: "Are you sure you want to delete this loan record?",
    prestamo_title: "Loan Management",
    prestamo_actualizar_estado: "Update Loan Status",
    prestamo_registrar_nuevo: "Register New Loan",
    prestamo_usuario: "User (Borrower):",
    prestamo_selecciona_usuario: "Select a user",
    prestamo_estado_prestamo: "Loan Status:",
    prestamo_activo: "Active",
    prestamo_devuelto: "Returned",
    prestamo_atrasado: "Overdue",
    prestamo_btn_actualizar: "Update Status",
    prestamo_btn_registrar: "Register Loan",
    prestamo_historial: "Loan History",
    prestamo_col_fecha_prestamo: "Loan Date",
    prestamo_col_fecha_devolucion: "Return Date",
    prestamo_resolver: "Resolve",
    prestamo_no_registrados: "No loans registered",

    // Registrar salida
    salida_disp_no_existe: "Device does not exist",
    salida_solo_mantenimiento: "You can only register an exit if the device is in maintenance.",
    salida_err_registrar: "Error registering exit",
    salida_confirm_finalizar: "End device process?",
    salida_title: "Register Device Exit",
    salida_subtitle: "Manage equipment exits when their process finishes",
    salida_btn_registrar: "Register Exit",
    salida_editar: "Edit Exit",
    salida_modal_title: "Register Device Exit",
    cerrar: "Close",
    salida_modal_serial: "Device Serial",
    salida_modal_serial_ph: "E.g. ABC-123456",
    salida_modal_info: "Information",
    salida_modal_info_desc: "The exit is registered automatically (date, time, and status).",
    salida_btn_actualizar: "Update Exit",
    salida_buscar_ph: "Search by serial, name...",
    salida_col_fecha_ent: "Entry Date",
    salida_col_fecha_sal: "Exit Date",
    salida_no_registros: "No records found",

    // Reportes
    reportes_err_fechas: "Please select From and To dates to continue.",
    reportes_err_excel_usuarios: "Error downloading Users Excel",
    reportes_err_pdf_usuarios: "Error downloading Users PDF",
    reportes_err_excel_disp: "Error downloading Devices Excel",
    reportes_err_pdf_disp: "Error downloading Devices PDF",
    id: "ID",
    reportes_fecha_creacion: "Creation Date",
    reportes_title: "Generate Reports",
    reportes_exportar: "Export reports",
    reportes_subtitle: "Generate reports according to your needs",
    reportes_reg_vista: "Records in preview",
    reportes_generados: "Generated reports",
    reportes_vista_previa: "Preview",
    reportes_buscar_usu: "Search by name, email, or role...",
    reportes_buscar_disp: "Search by name, serial, status, or user...",
    reportes_cargando: "Loading data...",
    reportes_no_registros: "No records found.",
    reportes_rep_usuarios: "Users Report",
    reportes_todos: "All",
    reportes_tecnicos: "Technicians",
    reportes_desde: "From",
    reportes_hasta: "To",
    reportes_gen_excel: "Generate Excel",
    reportes_gen_pdf: "Generate PDF",
    reportes_rep_disp: "Devices Report",
    reportes_vista_usu: "Preview — Users",
    reportes_vista_disp: "Preview — Devices",
    reportes_han_sido_generados: "reports have been generated in total",

    // Usuarios
    usu_eliminar_confirm: "Are you sure you want to delete this user?",
    usu_title: "User Management",
    usu_registrar_nuevo: "Register New User",
    usu_form_nombre: "Name:",
    usu_form_correo: "Email Address:",
    usu_form_pass: "Password:",
    usu_form_rol: "Role:",
    usu_estandar: "Standard User",
    usu_actualizar: "Update User",
    usu_registrar: "Register User",
    usu_no_registrados: "No users registered",

    // Perfil
    perfil_pwd_actualizada: "Password updated",
    perfil_err_pwd: "Error changing password",
    perfil_cambiar_pwd: "Change password",
    perfil_nueva_pwd: "New password",
    perfil_btn_pwd: "Update password",
    perfil_correo_actualizado: "Email updated successfully",
    perfil_err_correo: "Error updating email",
    perfil_cambiar_correo: "Change Email",
    perfil_nuevo_correo: "New email",
    perfil_btn_correo: "Update email",

    // Calendario
    cal_titulo: "Calendar",
    cal_hoy: "Today",
    cal_agregar_evento: "+ Add event",
    cal_sin_eventos_dia: "No events this day",
    cal_sin_eventos_mes: "No events this month",
    cal_eventos_mes: "Events of the month",
    cal_entrega: "Delivery:",
    cal_sin_ubicacion: "No location",
    cal_mas: "more",
    cal_registrar_entrega: "Register delivery",
    cal_registrar_mantenimiento: "Register maintenance",
    cal_registrar_salida: "Register checkout",
    cal_modal_registrar_entrega: "Register Delivery",
    cal_modal_registrar_mantenimiento: "Register Maintenance",
    cal_modal_registrar_salida: "Register Checkout",
    cal_accion_registrada: "Action registered successfully.",
    cal_err_registrar_accion: "Error registering action. Try again.",
    cal_modal_agregar_title: "Add committed date",
    cal_dispositivo_label: "Device",
    cal_selecciona_equipo: "Select equipment...",
    cal_fecha_estimada: "Estimated delivery date",
    cal_nota_opcional: "Note (optional)",
    cal_nota_ph: "Ex: waiting for parts, client calls on Friday...",
    cal_guardar: "Save ↗",
    cal_confirmar_accion: "Confirm this action? State will change to",
    cal_guardando: "Saving…",
    cal_confirmar_btn: "✓ Confirm",
    cal_detalle_equipo: "Equipment Detail",
    ene: "January", feb: "February", mar: "March", abr: "April", may: "May", jun: "June", jul: "July", ago: "August", sep: "September", oct: "October", nov: "November", dic: "December",
    dom: "Sun", lun: "Mon", mar_dia: "Tue", mie: "Wed", jue: "Thu", vie: "Fri", sab: "Sat",
    // Asignaciones
    asignacion_title: "Task Assignment",
    asignacion_sin_tecnicos: "No technicians available.",
    asignacion_sin_dispositivos: "No devices pending assignment.",
    asignacion_tecnicos_disponibles: "Available Technicians",
    asignacion_tareas_activas: "active tasks",
    asignacion_btn_asignar: "Assign",
    asignacion_seleccionar_tecnico: "Select technician...",
    asignacion_exito: "Device assigned successfully",
    asignacion_error: "Error assigning device",
    asignacion_pendientes: "Pending Devices",

    // Dispositivos (claves específicas del módulo)
    disp_banner_titulo: "Register\nNew Devices",
    disp_banner_sub: "Register and save new devices in the system",
    disp_reingresar: "Re-enter Device",
    disp_lista: "Device list",
    disp_registrados: "registered",
    disp_buscar_placeholder: "Search by name, serial or brand...",
    disp_todos_estados: "All statuses",
    disp_serial: "Serial",
    disp_marca: "Brand",
    disp_ubicacion: "Location",
    disp_fecha_hora: "Date / Time",
    disp_acciones: "Actions",
    disp_en_revision: "Under Review",
    disp_imagen: "Device image",
    disp_guardando: "Saving...",
    disp_actualizar: "Update device",
    disp_editar: "Edit device",
    disp_registrar_nuevo: "Register new device",
    disp_no_registrado: "Device is not registered",
    disp_error_reingreso: "Error re-entering device",
    disp_serial_label: "Device serial",
    disp_procesando: "Processing...",
    disp_confirmar_reingreso_btn: "Confirm Re-entry",
    disp_sin_resultados: "No devices match the filters",
    disp_confirmar_reingreso: "Do you want to re-enter this device?",
    disp_estado_cambiara: "Its status will change to",
    disp_descripcion: "Equipment description",
    disp_col_tipo: "Type",
    disp_col_nombre_disp: "Device Name",

    // Additional keys
    correo_col_correo: "Email",
    rol: "Role",
    agregar: "Add",
    cargando_info: "Loading information...",
    dash_usuarios: "Users",
    dash_dispositivos: "Devices",
    rpt_rol_superadmin: "Super Admin",
    rpt_rol_tecnico: "Technician",
    rpt_rol_usuario: "User",

    // Sidebar
    sidebar_simular_usuario: "Simulate user",
    sidebar_simulando_como: "👁 Simulating as:",
    sidebar_volver_admin: "← Back to Super Admin",
    sidebar_seleccionar_usuario: "Select user...",
    sidebar_buscar_usuario: "Search user or technician...",
    sidebar_disp_asignados: "Assigned devices",
    sidebar_sin_disp_pendientes: "No pending devices",
    sidebar_disp_asignado: "Assigned device",
    sidebar_al_confirmar: "Upon confirming, the device will move to",
    sidebar_en_mantenimiento_bold: "In Maintenance",
    sidebar_comenzaras: "and you will start working on it.",
    sidebar_guardando: "Saving...",
    sidebar_iniciar_mant: "✓ Start maintenance",
    sidebar_tecnicos: "Technicians",
    sidebar_usuarios: "Users",
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'es';
  });

  const t = (key) => {
    return translations[language][key] || key;
  };

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
